Added -f function to specify filename.

diff --git a/fsed b/fsed
--- a/fsed
+++ b/fsed
@@ -18,6 +18,8 @@ Options:
     -d dirname          If dirname is a valid path to a directory, it 
                         selects that directory to operate on instead
                         (default is working directory)
+    -f filename         If filename is a valid path to a file, it 
+                        selects only that file to operate on.
 EOF
 }
 
@@ -33,12 +35,20 @@ if [ "$1" == "--help" ]; then
 	exit 1
 fi
 
-if [ "$1" == "-d" ]; then
+if [ "$1" == "-d" ] || [ "$1" == "-f" ]; then
 	# user-specified directory
 	altDir="$2"
-	prefix="$2"
-	if [ ! -d $altDir ]; then
+	if [ "$1" == "-d" ]; then
+		prefix="$2"
+	else
+		prefix=""
+	fi
+
+	if [ ! -d $altDir ] && [ "$1" == "-d" ]; then
 		echo "Error: directory $altDir not found." >&2
+		exit 1
+	elif [ ! -f $altDir ] && [ "$1" == "-f" ]; then # altDir is a file here
+		echo "Error: file $altDir not found." >&2
 		exit 1
 	else
 		origRegex="$3"
@@ -50,7 +60,7 @@ else
 	canary="$3" # should be blank
 fi
 
-fileList=(`ls $altDir`)
+fileList=(`ls $altDir`) # handles -d, -f, and default case
 
 if [ -n "$canary" ] ; then # canary isn't blank
 	echo "Error: fsed cannot take $# arguments." >&2
@@ -58,7 +68,9 @@ if [ -n "$canary" ] ; then # canary isn't blank
 fi
 
 # change to altdir (changes not saved after exit)
-cd $altDir
+if [ "$1" == "-d" ]; then
+	cd $altDir
+fi
 
 wereChanges=0
 for k in "${fileList[@]}"; do
